### ISSUE TITLE
Hard to close some modals.

### ISSUE THREAD

**Issue by ArvinoDorito** [codefez/codefez.github.io#27]
I have found a fix.
We can add a button underneath here: 
```
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>
```

Which is:
`  <button onclick="example_modal.close()" class="btn">Close</button>`

It gives us:
```
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
  <button onclick="example_modal.close()" class="btn">Close</button>

</dialog>
```

![image](https://github.com/user-attachments/assets/05b9b8e6-8394-4d3d-a0df-a0dfac274a62)

**Comment by bitFez** [comment]
We will add this to every modal instead

<form method="dialog">
      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
    </form>
